This is a testharness.js-based test.
PASS Errors must be propagated backward: starts errored; preventCancel omitted; fulfilled cancel promise
PASS Errors must be propagated backward: becomes errored before piping due to write; preventCancel omitted; fulfilled cancel promise
PASS Errors must be propagated backward: becomes errored before piping due to write; preventCancel omitted; rejected cancel promise
PASS Errors must be propagated backward: becomes errored before piping due to write; preventCancel = undefined (falsy); fulfilled cancel promise
PASS Errors must be propagated backward: becomes errored before piping due to write; preventCancel = null (falsy); fulfilled cancel promise
PASS Errors must be propagated backward: becomes errored before piping due to write; preventCancel = false (falsy); fulfilled cancel promise
PASS Errors must be propagated backward: becomes errored before piping due to write; preventCancel = 0 (falsy); fulfilled cancel promise
PASS Errors must be propagated backward: becomes errored before piping due to write; preventCancel = -0 (falsy); fulfilled cancel promise
PASS Errors must be propagated backward: becomes errored before piping due to write; preventCancel = NaN (falsy); fulfilled cancel promise
PASS Errors must be propagated backward: becomes errored before piping due to write; preventCancel =  (falsy); fulfilled cancel promise
PASS Errors must be propagated backward: becomes errored before piping due to write; preventCancel = true (truthy)
PASS Errors must be propagated backward: becomes errored before piping due to write; preventCancel = a (truthy)
PASS Errors must be propagated backward: becomes errored before piping due to write; preventCancel = 1 (truthy)
PASS Errors must be propagated backward: becomes errored before piping due to write; preventCancel = Symbol() (truthy)
PASS Errors must be propagated backward: becomes errored before piping due to write; preventCancel = [object Object] (truthy)
PASS Errors must be propagated backward: becomes errored before piping due to write, preventCancel = true; preventAbort = true
PASS Errors must be propagated backward: becomes errored before piping due to write; preventCancel = true, preventAbort = true, preventClose = true
PASS Errors must be propagated backward: becomes errored during piping due to write; preventCancel omitted; fulfilled cancel promise
PASS Errors must be propagated backward: becomes errored during piping due to write; preventCancel omitted; rejected cancel promise
PASS Errors must be propagated backward: becomes errored during piping due to write; preventCancel = true
PASS Errors must be propagated backward: becomes errored during piping due to write, but async; preventCancel = false; fulfilled cancel promise
PASS Errors must be propagated backward: becomes errored during piping due to write, but async; preventCancel = false; rejected cancel promise
PASS Errors must be propagated backward: becomes errored during piping due to write, but async; preventCancel = true
PASS Errors must be propagated backward: becomes errored after piping; preventCancel omitted; fulfilled cancel promise
PASS Errors must be propagated backward: becomes errored after piping; preventCancel omitted; rejected cancel promise
PASS Errors must be propagated backward: becomes errored after piping; preventCancel = true
PASS Errors must be propagated backward: becomes errored after piping due to last write; source is closed; preventCancel omitted (but cancel is never called)
PASS Errors must be propagated backward: becomes errored after piping due to last write; source is closed; preventCancel = true
PASS Errors must be propagated backward: becomes errored after piping; dest never desires chunks; preventCancel = false; fulfilled cancel promise
PASS Errors must be propagated backward: becomes errored after piping; dest never desires chunks; preventCancel = false; rejected cancel promise
PASS Errors must be propagated backward: becomes errored after piping; dest never desires chunks; preventCancel = true
FAIL Errors must be propagated backward: becomes errored before piping via abort; preventCancel omitted; fulfilled cancel promise assert_equals: the promise must reject with error1 expected object "error1: error1!" but got object "TypeError: The stream is in the process of being aborted"
FAIL Errors must be propagated backward: becomes errored before piping via abort; preventCancel omitted; rejected cancel promise assert_equals: the promise must reject with error1 expected object "error1: error1!" but got object "TypeError: The stream is in the process of being aborted"
FAIL Errors must be propagated backward: becomes errored before piping via abort; preventCancel = true assert_throws: function "function() { throw e }" threw object "TypeError: The stream is in the process of being aborted" ("TypeError") expected object "error1: error1!" ("error1")
PASS Errors must be propagated backward: erroring via the controller errors once pending write completes
Harness: the test ran to completion.

