This is a testharness.js-based test.
PASS Background Fetch API: BackgroundFetchFailEvent tests 
FAIL Verifies that the BackgroundFetchFailEvent can be constructed. Test bug: need to pass exception to assert_throws()
Harness: the test ran to completion.

