This is a testharness.js-based test.
Harness Error. harness_status.status = 1 , harness_status.message = 1 duplicate test name: "throw a 'SecurityError' when construct sensor in an insecure context"
PASS throw a 'SecurityError' when construct sensor in an insecure context 
PASS throw a 'SecurityError' when construct sensor in an insecure context 
Harness: the test ran to completion.

