This is a testharness.js-based test.
FAIL Synchronously signaled abort. promise_test: Unhandled rejection with value: object "ReferenceError: NFCReader is not defined"
Harness: the test ran to completion.

