This is a testharness.js-based test.
PASS Test that cross-origin access on a detached window throws a SecurityError.
FAIL method call with detached window receiver should throw assert_throws: function "function () {\n      window.requestAnimationFrame.call(detachedWindow, function () { });\n    }" did not throw
FAIL attribute access with detached window receiver should throw assert_throws: function "function () {\n      Object.getOwnPropertyDescriptor(window, "document").get.call(detachedWindow);\n    }" did not throw
Harness: the test ran to completion.

